### ISSUE TITLE
Unset keys from variable dicts

### ISSUE THREAD

**Issue by namedgraph** [lariel-fernandes/mlopus#12]
Hi @lariel-fernandes 👋  Long time no see. BTW I want to visit your city again in May :)

I was wondering about such scenario:

parameters.yml
```yaml
model_config: ${model_config}
```

variables.yml
```yaml
model_config:
  ...
  embed_type: llama_index.embeddings.azure_openai.base.AzureOpenAIEmbedding
  embed_conf:
    model: "text-embedding-ada-002"
    deployment_name: "text-embedding-ada-002"
    api_version: "2023-05-15"
    model_name: "" # for HuggingFaceEmbedding compatibility
```

Unit test:
```python
    with temp_session(
        env="local",
        overrides={
            ...
            "model_config": {
                "embed_type": "llama_index.embeddings.huggingface.HuggingFaceEmbedding",
                "embed_conf": {
                    "model_name": "BAAI/bge-base-en",
                },
                # don't need "model" and "deployment_name" and "api_version" copied here
            },
        },
    ):
```

Is it somehow possible to avoid the deep-copy of variable dicts when doing overrides? Or somehow unset specific keys?

I want to override `AzureOpenAIEmbedding` config with `HuggingFaceEmbedding` config but the OpenAI-specific fields such as `deployment_name` and `api_version` are causing Pydantic issues when it is being instantiated:
```
TypeError: HuggingFaceEmbedding.__init__() got an unexpected keyword argument 'deployment_name'
```
